abbr --command jj -a bmc -- "bookmark create"
abbr --command jj --set-cursor -a why -- "log -r 'why_immutable(%)'"
abbr --command jj -a wus -- "workspace update-stale"
abbr --command jj -a last -- "op show -p"
abbr --set-cursor --command jj -a m -- "describe -m '%'"
abbr --command jj --set-cursor -a rg -- "log --patch -r 'diff_lines(\"*%*\")'"
abbr --command jj --set-cursor -a fd -- "log -r 'diff_lines(\"*%*\")'"
abbr --command jj --set-cursor -a ff -- "file search -p '*%*' -r 'all()'"
abbr --set-cursor -a jjrg -- "jjui -r 'diff_lines(\"*%*\")'"
