name: comp-vision
channels: 
        - conda-forge
dependencies:
        - python
        - numpy
        - scipy
        - matplotlib
        - ipykernel
        - pip
        - opencv
        - numba
        - black
