name: optimal-control
channels: 
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - cvxpy
  - matplotlib
  - ipykernel
  - pip
  - opencv
  - numba
  - black
  - casadi
  - pip:
    - gradient-free-optimizers 
