#!/usr/bin/env fish
sudo apt-get install -y \
    cmake \
    ninja-build \
    openocd\
    sublime-merge \
    anydesk \
    neovim \
    x11-xserver-utils \
    thefuck \
    libudev-dev \
    libusb-dev \
    libcairo2-dev \
    libjpeg-dev \
    libgif-dev \
    texlive-full \
    python3-pip \
    sublime-merge \
    libpango1.0-dev \
    librsvg2-dev \
    libssl-dev \
    libxcb1-dev \
    libxcb-render0-dev \
    libxcb-shape0-dev \
    libxcb-xfixes0-dev \
    libgl1-mesa-glx \
    libegl1-mesa \
    libxrandr2 \
    libxrandr2 \
    libxss1 \
    libxcursor1 \
    libxcomposite1 \
    libasound2 \
    libxi6 \
    libxtst6 \
    clang \
    libclang-dev \
    meson \
    sshpass \
    ffmpeg
