[alias]     # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
br = "build --release"
wc = "watch -x check --clear"

[build]
rustflags = ["-C", "target-cpu=native", "-Z", "share-generics=y"]

#[target.x86_64-unknown-linux-gnu]
#linker = "rust-lld"
