[alias]     # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
br = "build --release"
wc = "watch -x check --clear"

[build]
rustflags = [ "-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
#opt-level = 1
split-debuginfo = "unpacked"

[profile.release]
lto = true
panic = 'abort'
# split-debuginfo = "unpacked"

[profile.test]
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.test.package."*"]
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang" 
rustflags = [
    "-C", "link-arg=-fuse-ld=/home/amedhi/.local/bin/mold",
    # "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld", 
    "-C", "target-feature=+crt-static", "-C", "link-self-contained=yes",
    "-C", "target-cpu=native",
]
#linker = "rust-lld"

#[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-run"
