cargo install bandwhich
cargo install bat
cargo install bottom
cargo install broot
cargo install cargo-binutils
cargo install cargo-do
cargo install cargo-edit
cargo install cargo-generate
cargo install cargo-outdated
cargo install cargo-update
cargo install cargo-watch
cargo install drone
cargo install du-dust
cargo install dua
cargo install eva
cargo install exa
cargo install fd-find
cargo install flamegraph
cargo install flip-link
cargo install gfold
cargo install git-delta
cargo install gitui
cargo install huniq
cargo install hyperfine
cargo install lsd
cargo install mdbook
cargo install mdcat
cargo install pipe-rename
cargo install probe-run
cargo install procs
cargo install ptail
cargo install pueue
cargo install ripgrep
cargo install rustfilt
cargo install sd
cargo install serial-monitor
cargo install shy
cargo install so
cargo install spotify-tui
cargo install starship
cargo install tealdeer
cargo install verco
cargo install watchexec
cargo install zoxide
cargo install-update
