format = """
$directory\
$jobs\
$shlvl\
$time\
$git_branch$git_status$git_state\
$docker_context\
$cmake\
$julia\
$rust\
$nodejs\
$conda$python\
$zig
$status$character"""

format2 = """
$status\
$jobs\
$shlvl\
$time\
$git_branch$git_status$git_state\
$docker_context\
$cmake\
$julia\
$rust\
$nodejs\
$conda$python\
$zig
$directory"""

add_newline = true

[directory]
format = "[$read_only]($read_only_style)[$path ]($style)[ ](blue)"
truncation_length = 3
#truncation_length = 1
truncation_symbol = "…/"
truncate_to_repo = true
style = "bold italic bright-white bg:blue"
fish_style_pwd_dir_length = 1

[time]
format = "[$time]($style fg:bright-yellow) "
disabled=false

[git_branch]
format="[$symbol$branch]($style) "
[git_status]
format='([$state($progress_current/$progress_total)]($style))'
[git_state]
format='([\[$all_status$ahead_behind\]]($style) )'	

[battery]
format = "[$symbol]($style bg:blue)"

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[character]                            
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[conda]
format = "[$symbol$environment]($style) "

[cmake]
format = "[$symbol$version]($style) "

[python]
format = "[${symbol}${pyenv_prefix}${version}($virtualenv)]($style) "
style = "bold bright-green"

[julia]
format = "[$symbol$version]($style) "

[nodejs]
format = "[$symbol$version]($style) "

[zig]
format = "[$symbol$version]($style) "

[rust]
format = "[$symbol$version]($style) "

defaultformat = """
($username@$hostname:)\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

