terminal:
  searchOptions: {}
  colorScheme:
    name: Argonaut
    foreground: '#fffaf4'
    background: '#0e1019'
    cursor: '#ff0018'
    colors:
      - '#232323'
      - '#ff000f'
      - '#8ce10b'
      - '#ffb900'
      - '#008df8'
      - '#6d43a6'
      - '#00d8eb'
      - '#ffffff'
      - '#444444'
      - '#ff2740'
      - '#abe15b'
      - '#ffd242'
      - '#0092ff'
      - '#9a5feb'
      - '#67fff0'
      - '#ffffff'
  ligatures: false
  background: colorScheme
  cursor: beam
  font: FiraCode NF
hotkeys:
  profile: {}
  shell: {}
serial: {}
ssh: {}
appearance:
  frame: native
  theme: Compact
  flexTabs: true
enableWelcomeTab: false
pluginBlacklist: []
