set shell := ["fish", "-c"]
wd := invocation_directory()

@_default: 
    just -f {{justfile()}} -l

@edit:
    cd {{justfile_directory()}} && nvim {{justfile()}}

@new-lets name:
    cp {{justfile_directory()}}/template {{justfile_directory()}}/{{name}}.just
    nvim {{justfile_directory()}}/{{name}}.just

@config-nvim:
    cd .config/nvim && $EDITOR .config/nvim/init.lua

@config-fish:
    cd .config/fish && $EDITOR .config/fish/config.fish

@config-edit:
    nvim (fd -IH --type f '.' ~/.config/ | fzf)

